services:
  cc-term-flask:
    build: .
    container_name: cc-term-flask
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - ./.local:/app/.local

  nginx:
    build:
      context: ..
      dockerfile: infra-was/Dockerfile.nginx
    container_name: cc-term-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - cc-term-flask
